#!/usr/bin/env bash
# Function to display information about a specific subdomain

display_info() {
  domain="$1"
  subdomain="$2"
  dig "$subdomain.$domain" | awk '/ANSWER SECTION:/{getline; printf "The subdomain %s is a %s record and points to %s\n", var, $4, $5}' var="$subdomain"
}

# Check if only domain is provided, or both domain and subdomain are provided
if [ $# -eq 1 ]; then
  # When only domain is provided, display information for its subdomains www, lb-01, web-01 and web-02
  for subdomain in "www" "lb-01" "web-01" "web-02"; do
    display_info "$1" "$subdomain"
  done
elif [ $# -eq 2 ]; then
  # When domain and subdomain parameters are provided, display information for the specified subdomain
  display_info "$1" "$2"
else
  # Invalid number of arguments
  echo "Error: Invalid number of arguments"
  exit 1
fi
