#!/usr/bin/env bash
# Install nginx using apt-get

apt-get update
apt-get -y install nginx

# Configure nginx to listen on port 80
sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Restart nginx to apply configuration changes
service nginx restart

# Create index.html with "Hello World!"
echo "Hello World!" > /var/www/html/index.html

