#!/usr/bin/env bash
# Install Nginx if it is not yet installed

if ! which nginx > /dev/null; then
  sudo apt-get -y update
  sudo apt-get -y install nginx
fi

# Replace the line with multiple lines in /etc/nginx/sites-available/default
sudo sed -i '/^        location \/ {/a \        location \/redirect_me {\n            return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n        }' /etc/nginx/sites-available/default

# Reload Nginx to apply changes
sudo service nginx reload

