#!/usr/bin/env bash
# This script adds an "X-Served-By" to the response header

# Installing the nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Adds the header "X-Served-By: $hostname"
sudo sed -i "/http {/a \        add_header X-Served-By \$hostname;" /etc/nginx/nginx.conf

# Restarts nginx
sudo service nginx restart

