#!/usr/bin/env bash
# This script installs HAproxy and sets up a load balancer
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown -R "$USER:$USER" /etc/haproxy/
echo -e "frontend zenitsu\n\tbind *:80\n\tdefault_backend tanjiro\n\nbackend tanjiro\n\tbalance roundrobin\n\tserver 146366-web-01 100.26.173.94:80 check\n\tserver 146366-web-02 35.153.79.52:80 check\n" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
