#!/usr/bin/env bash
# This script configures the container to run Nginx as the nginx user and listen on port 8080
sudo chown nginx /etc/nginx/nginx.conf
sudo chmod u+rw /etc/nginx/nginx.conf
pkill apache
sudo sed -i 's/80 default_server/8080 default_server/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
